spring:
  application:
    name: chatop-web-service
  # MariaDB configuration
  datasource:
    hikari:
      connection-timeout: 3000
  # Spring JPA configuration
  jpa:
    show-sql: true
    # Ensure that Hibernate session is active during HTTP request
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        # Use exact table names (case-sensitive) as specified by @Table (name = "xyz") directive
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    mapper:
      default-view-inclusion: false
springdoc:
  swagger-ui:
    url: /openapi.yml
  api-docs:
    enabled: true